In [1]:
from IPython.display import display
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

In [2]:
INPUT_FILE = Path(
    r"C:\Users\bhara\OneDrive\Desktop\DAMO-699-Capstone-Project-Unofficial-\DAMO-699-Capstone-Project-Unofficial-\data\optimized\CTAS_Triage.csv"
)

OUTPUT_FOLDER = Path(
    r"C:\Users\bhara\OneDrive\Desktop\DAMO-699-Capstone-Project-Unofficial-\DAMO-699-Capstone-Project-Unofficial-\data\Explorer Dataset"
)

OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)

OUTPUT_FILE = OUTPUT_FOLDER / "CTAS_Triage.csv"

In [3]:
df = pd.read_csv(INPUT_FILE)

print("CTAS TRIAGE DATASET LOADED SUCCESSFULLY")

CTAS TRIAGE DATASET LOADED SUCCESSFULLY

In [4]:
print("\nFIRST 10 ROWS")
display(df.head(10))

print("\nLAST 10 ROWS")
display(df.tail(10))

FIRST 10 ROWS

,fiscal_year,sex,triage_level,age_group,ed_visits,median_length_of_stay_min,fiscal_year_start,length_of_stay_hours,ctas_urgency_score,age_broad_category
0,2021-2022,All,Resuscitation,00–19,22758,234.0,2021,3.9,1,Adult
1,2021-2022,All,Resuscitation,20–44,29926,336.0,2021,5.6,1,Adult
2,2021-2022,All,Resuscitation,45–64,32434,312.0,2021,5.2,1,Adult
3,2021-2022,All,Resuscitation,65+,56151,384.0,2021,6.4,1,Senior
4,2021-2022,All,Resuscitation,Total,141657,318.0,2021,5.3,1,Adult
5,2021-2022,All,Emergent,00–19,421027,216.0,2021,3.6,2,Adult
6,2021-2022,All,Emergent,20–44,779127,276.0,2021,4.6,2,Adult
7,2021-2022,All,Emergent,45–64,656244,312.0,2021,5.2,2,Adult
8,2021-2022,All,Emergent,65+,694042,414.0,2021,6.9,2,Senior
9,2021-2022,All,Emergent,Total,2551278,306.0,2021,5.1,2,Adult

LAST 10 ROWS

,fiscal_year,sex,triage_level,age_group,ed_visits,median_length_of_stay_min,fiscal_year_start,length_of_stay_hours,ctas_urgency_score,age_broad_category
1700,2003-2004,Male,Non-urgent,00–19,94000,65.0,2003,1.08,3,Adult
1701,2003-2004,Male,Non-urgent,20–44,137821,72.0,2003,1.20,3,Adult
1702,2003-2004,Male,Non-urgent,45–64,82423,67.0,2003,1.12,3,Adult
1703,2003-2004,Male,Non-urgent,65+,48303,66.0,2003,1.10,3,Senior
1704,2003-2004,Male,Non-urgent,Total,362547,68.0,2003,1.13,3,Adult
1705,2003-2004,Male,Unknown,00–19,201,35.0,2003,0.58,3,Adult
1706,2003-2004,Male,Unknown,20–44,264,31.0,2003,0.52,3,Adult
1707,2003-2004,Male,Unknown,45–64,103,44.0,2003,0.73,3,Adult
1708,2003-2004,Male,Unknown,65+,50,27.0,2003,0.45,3,Senior
1709,2003-2004,Male,Unknown,Total,618,32.5,2003,0.54,3,Adult

In [5]:
print("\nShape")
print(df.shape)

print("\nColumn Names")
print(df.columns.tolist())

print("\nData Types")
print(df.dtypes)

print("\nMissing Values")
display(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

Shape
(1710, 10)

Column Names
['fiscal_year', 'sex', 'triage_level', 'age_group', 'ed_visits', 'median_length_of_stay_min', 'fiscal_year_start', 'length_of_stay_hours', 'ctas_urgency_score', 'age_broad_category']

Data Types
fiscal_year                      str
sex                              str
triage_level                     str
age_group                        str
ed_visits                      int64
median_length_of_stay_min    float64
fiscal_year_start              int64
length_of_stay_hours         float64
ctas_urgency_score             int64
age_broad_category               str
dtype: object

Missing Values

fiscal_year                  0
sex                          0
triage_level                 0
age_group                    0
ed_visits                    0
median_length_of_stay_min    0
fiscal_year_start            0
length_of_stay_hours         0
ctas_urgency_score           0
age_broad_category           0
dtype: int64

Duplicate Rows
0

In [6]:
print("\nSummary Statistics")
display(df.describe(include="all"))

Summary Statistics

,fiscal_year,sex,triage_level,age_group,ed_visits,median_length_of_stay_min,fiscal_year_start,length_of_stay_hours,ctas_urgency_score,age_broad_category
count,1710,1710,1710,1710,1.710000e+03,1710.000000,1710.000000,1710.000000,1710.000000,1710
unique,19,3,6,5,NaN,NaN,NaN,NaN,NaN,2
top,2021-2022,All,Resuscitation,00–19,NaN,NaN,NaN,NaN,NaN,Adult
freq,90,570,285,342,NaN,NaN,NaN,NaN,NaN,1368
mean,NaN,NaN,NaN,NaN,4.111702e+05,165.715789,2012.000000,2.761942,2.500000,NaN
std,NaN,NaN,NaN,NaN,6.877875e+05,92.662706,5.478828,1.544337,0.763986,NaN
min,NaN,NaN,NaN,NaN,4.500000e+01,10.000000,2003.000000,0.170000,1.000000,NaN
25%,NaN,NaN,NaN,NaN,2.363025e+04,83.000000,2007.000000,1.380000,2.000000,NaN
50%,NaN,NaN,NaN,NaN,1.666105e+05,144.000000,2012.000000,2.400000,3.000000,NaN
75%,NaN,NaN,NaN,NaN,4.961995e+05,240.000000,2017.000000,4.000000,3.000000,NaN
max,NaN,NaN,NaN,NaN,6.393422e+06,420.000000,2021.000000,7.000000,3.000000,NaN

In [7]:
print("\nFiscal Years")
display(df["fiscal_year"].value_counts())

print("\nSex Categories")
display(df["sex"].value_counts())

print("\nTriage Levels")
display(df["triage_level"].value_counts())

print("\nAge Groups")
display(df["age_group"].value_counts())

print("\nCTAS Scores")
display(df["ctas_urgency_score"].value_counts())

Fiscal Years

fiscal_year
2021-2022    90
2020-2021    90
2019-2020    90
2018-2019    90
2017-2018    90
2016-2017    90
2015-2016    90
2014-2015    90
2013-2014    90
2012-2013    90
2011-2012    90
2010-2011    90
2009-2010    90
2008-2009    90
2007-2008    90
2006-2007    90
2005-2006    90
2004-2005    90
2003-2004    90
Name: count, dtype: int64

Sex Categories

sex
All       570
Female    570
Male      570
Name: count, dtype: int64

Triage Levels

triage_level
Resuscitation    285
Emergent         285
Urgent           285
Less urgent      285
Non-urgent       285
Unknown          285
Name: count, dtype: int64

Age Groups

age_group
00–19    342
20–44    342
45–64    342
65+      342
Total    342
Name: count, dtype: int64

CTAS Scores

ctas_urgency_score
3    1140
1     285
2     285
Name: count, dtype: int64

In [8]:
print("\nED Visits Summary")
display(df["ed_visits"].describe())

print("\nMedian LOS Summary")
display(df["median_length_of_stay_min"].describe())

print("\nFiscal Year Start Summary")
display(df["fiscal_year_start"].describe())

ED Visits Summary

count    1.710000e+03
mean     4.111702e+05
std      6.877875e+05
min      4.500000e+01
25%      2.363025e+04
50%      1.666105e+05
75%      4.961995e+05
max      6.393422e+06
Name: ed_visits, dtype: float64

Median LOS Summary

count    1710.000000
mean      165.715789
std        92.662706
min        10.000000
25%        83.000000
50%       144.000000
75%       240.000000
max       420.000000
Name: median_length_of_stay_min, dtype: float64

Fiscal Year Start Summary

count    1710.000000
mean     2012.000000
std         5.478828
min      2003.000000
25%      2007.000000
50%      2012.000000
75%      2017.000000
max      2021.000000
Name: fiscal_year_start, dtype: float64

In [9]:
print("DATA QUALITY REPORT")

DATA QUALITY REPORT

In [10]:
print(f"Rows               : {df.shape[0]}")
print(f"Columns            : {df.shape[1]}")
print(f"Duplicate Rows     : {df.duplicated().sum()}")
print(f"Missing Cells      : {df.isnull().sum().sum()}")

print("\nMissing Values by Column")
display(df.isnull().sum())

Rows               : 1710
Columns            : 10
Duplicate Rows     : 0
Missing Cells      : 0

Missing Values by Column

fiscal_year                  0
sex                          0
triage_level                 0
age_group                    0
ed_visits                    0
median_length_of_stay_min    0
fiscal_year_start            0
length_of_stay_hours         0
ctas_urgency_score           0
age_broad_category           0
dtype: int64

In [11]:
print("\nRemoving 'All' from Sex...")

df["sex"] = (
    df["sex"]
    .astype(str)
    .str.strip()
)

df = df[df["sex"].str.lower() != "all"].copy()

print("Remaining Sex Categories")
print(df["sex"].value_counts())

Removing 'All' from Sex...
Remaining Sex Categories
sex
Female    570
Male      570
Name: count, dtype: int64

In [12]:
print("\nRemoving 'Total' Age Group...")

df["age_group"] = (
    df["age_group"]
    .astype(str)
    .str.strip()
)

df = df[df["age_group"].str.lower() != "total"].copy()

print(df["age_group"].value_counts())

Removing 'Total' Age Group...
age_group
00–19    228
20–44    228
45–64    228
65+      228
Name: count, dtype: int64

In [13]:
print("\nRenaming Columns...")

df.rename(
    columns={
        "median_length_of_stay_min": "median_los_minutes",
        "length_of_stay_hours": "median_los_hours",
        "age_broad_category": "population_category"
    },
    inplace=True
)

print(df.columns.tolist())

Renaming Columns...
['fiscal_year', 'sex', 'triage_level', 'age_group', 'ed_visits', 'median_los_minutes', 'fiscal_year_start', 'median_los_hours', 'ctas_urgency_score', 'population_category']

In [14]:
print("\nConverting Median LOS to Whole Numbers...")

df["median_los_minutes"] = (
    pd.to_numeric(
        df["median_los_minutes"],
        errors="coerce"
    )
    .round(0)
    .astype(int)
)

Converting Median LOS to Whole Numbers...

In [15]:
df["median_los_hours"] = (
    df["median_los_minutes"] / 60
).round(2)

In [16]:
print("\nStandardizing CTAS Levels...")

ctas_mapping = {

    "Resuscitation":"CTAS I - Resuscitation",

    "Emergent":"CTAS II - Emergent",

    "Urgent":"CTAS III - Urgent",

    "Less Urgent":"CTAS IV - Less Urgent",

    "Non Urgent":"CTAS V - Non-Urgent",

    "Non-Urgent":"CTAS V - Non-Urgent"

}

df["triage_level"] = (
    df["triage_level"]
    .astype(str)
    .str.strip()
    .replace(ctas_mapping)
)

print(df["triage_level"].unique())

Standardizing CTAS Levels...
<ArrowStringArray>
['CTAS I - Resuscitation',     'CTAS II - Emergent',      'CTAS III - Urgent',
            'Less urgent',             'Non-urgent',                'Unknown']
Length: 6, dtype: str

In [17]:
print("\nCreating Population Category...")

df["population_category"] = np.where(
    df["age_group"].str.contains("00", na=False),
    "Pediatric & Youth",

    np.where(
        df["age_group"].str.contains("20", na=False),
        "Young Adult",

        np.where(
            df["age_group"].str.contains("45", na=False),
            "Middle Adult",

            np.where(
                df["age_group"].str.contains("65", na=False),
                "Older Adult",
                "Unknown"
            )
        )
    )
)

Creating Population Category...

In [18]:
print("\nAge Groups")
print(df["age_group"].value_counts())

print("\nPopulation Categories")
print(df["population_category"].value_counts())

print("\nCTAS Levels")
print(df["triage_level"].value_counts())

print("\nMedian LOS")
print(df["median_los_minutes"].describe())

print("\nPreview")

display(df.head(20))

Age Groups
age_group
00–19    228
20–44    228
45–64    228
65+      228
Name: count, dtype: int64

Population Categories
population_category
Pediatric & Youth    228
Young Adult          228
Middle Adult         228
Older Adult          228
Name: count, dtype: int64

CTAS Levels
triage_level
CTAS I - Resuscitation    152
CTAS II - Emergent        152
CTAS III - Urgent         152
Less urgent               152
Non-urgent                152
Unknown                   152
Name: count, dtype: int64

Median LOS
count    912.000000
mean     166.116228
std       94.261307
min       10.000000
25%       84.000000
50%      144.000000
75%      235.000000
max      420.000000
Name: median_los_minutes, dtype: float64

Preview

,fiscal_year,sex,triage_level,age_group,ed_visits,median_los_minutes,fiscal_year_start,median_los_hours,ctas_urgency_score,population_category
30,2021-2022,Female,CTAS I - Resuscitation,00–19,10332,240,2021,4.0,1,Pediatric & Youth
31,2021-2022,Female,CTAS I - Resuscitation,20–44,11051,330,2021,5.5,1,Young Adult
32,2021-2022,Female,CTAS I - Resuscitation,45–64,11653,324,2021,5.4,1,Middle Adult
33,2021-2022,Female,CTAS I - Resuscitation,65+,25787,414,2021,6.9,1,Older Adult
35,2021-2022,Female,CTAS II - Emergent,00–19,208386,228,2021,3.8,2,Pediatric & Youth
36,2021-2022,Female,CTAS II - Emergent,20–44,416879,282,2021,4.7,2,Young Adult
37,2021-2022,Female,CTAS II - Emergent,45–64,314935,306,2021,5.1,2,Middle Adult
38,2021-2022,Female,CTAS II - Emergent,65+,352317,414,2021,6.9,2,Older Adult
40,2021-2022,Female,CTAS III - Urgent,00–19,545195,180,2021,3.0,3,Pediatric & Youth
41,2021-2022,Female,CTAS III - Urgent,20–44,1146110,228,2021,3.8,3,Young Adult
42,2021-2022,Female,CTAS III - Urgent,45–64,727001,252,2021,4.2,3,Middle Adult
43,2021-2022,Female,CTAS III - Urgent,65+,880576,348,2021,5.8,3,Older Adult
45,2021-2022,Female,Less urgent,00–19,398170,144,2021,2.4,3,Pediatric & Youth
46,2021-2022,Female,Less urgent,20–44,677260,162,2021,2.7,3,Young Adult
47,2021-2022,Female,Less urgent,45–64,441281,168,2021,2.8,3,Middle Adult
48,2021-2022,Female,Less urgent,65+,398276,228,2021,3.8,3,Older Adult
50,2021-2022,Female,Non-urgent,00–19,121024,120,2021,2.0,3,Pediatric & Youth
51,2021-2022,Female,Non-urgent,20–44,223566,114,2021,1.9,3,Young Adult
52,2021-2022,Female,Non-urgent,45–64,145827,114,2021,1.9,3,Middle Adult
53,2021-2022,Female,Non-urgent,65+,115897,126,2021,2.1,3,Older Adult

In [19]:
print("\nSorting Dataset...")

df = (
    df.sort_values(
        by=[
            "fiscal_year_start",
            "ctas_urgency_score",
            "sex",
            "age_group"
        ],
        ascending=[False, True, True, True]
    )
    .reset_index(drop=True)
)

print("Dataset Sorted Successfully.")

Sorting Dataset...
Dataset Sorted Successfully.

In [20]:
print("\nReordering Columns...")

final_columns = [

    "fiscal_year",

    "fiscal_year_start",

    "sex",

    "triage_level",

    "ctas_urgency_score",

    "age_group",

    "population_category",

    "ed_visits",

    "median_los_minutes",

    "median_los_hours"

]

df = df[final_columns]

Reordering Columns...

In [21]:
print("Column Order Updated.")

Column Order Updated.

In [22]:
print(f"\nTotal Rows          : {len(df):,}")
print(f"Total Columns       : {len(df.columns)}")

print("\nColumn Names")
print(df.columns.tolist())

print("\nData Types")
print(df.dtypes)

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

Total Rows          : 912
Total Columns       : 10

Column Names
['fiscal_year', 'fiscal_year_start', 'sex', 'triage_level', 'ctas_urgency_score', 'age_group', 'population_category', 'ed_visits', 'median_los_minutes', 'median_los_hours']

Data Types
fiscal_year                str
fiscal_year_start        int64
sex                        str
triage_level               str
ctas_urgency_score       int64
age_group                  str
population_category        str
ed_visits                int64
median_los_minutes       int64
median_los_hours       float64
dtype: object

Missing Values
fiscal_year            0
fiscal_year_start      0
sex                    0
triage_level           0
ctas_urgency_score     0
age_group              0
population_category    0
ed_visits              0
median_los_minutes     0
median_los_hours       0
dtype: int64

Duplicate Rows
0

In [23]:
print("\nMemory Usage")
print(f"{df.memory_usage(deep=True).sum()/1024:.2f} KB")

Memory Usage
113.72 KB

In [24]:
print("\nUnique Fiscal Years")
print(sorted(df["fiscal_year"].unique(), reverse=True))

print("\nUnique Sex Categories")
print(df["sex"].unique())

print("\nUnique CTAS Levels")
print(df["triage_level"].unique())

print("\nUnique CTAS Scores")
print(df["ctas_urgency_score"].unique())

print("\nUnique Age Groups")
print(df["age_group"].unique())

print("\nUnique Population Categories")
print(df["population_category"].unique())

Unique Fiscal Years
['2021-2022', '2020-2021', '2019-2020', '2018-2019', '2017-2018', '2016-2017', '2015-2016', '2014-2015', '2013-2014', '2012-2013', '2011-2012', '2010-2011', '2009-2010', '2008-2009', '2007-2008', '2006-2007', '2005-2006', '2004-2005', '2003-2004']

Unique Sex Categories
<ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str

Unique CTAS Levels
<ArrowStringArray>
['CTAS I - Resuscitation',     'CTAS II - Emergent',      'CTAS III - Urgent',
            'Less urgent',             'Non-urgent',                'Unknown']
Length: 6, dtype: str

Unique CTAS Scores
[1 2 3]

Unique Age Groups
<ArrowStringArray>
['00–19', '20–44', '45–64', '65+']
Length: 4, dtype: str

Unique Population Categories
<ArrowStringArray>
['Pediatric & Youth', 'Young Adult', 'Middle Adult', 'Older Adult']
Length: 4, dtype: str

In [25]:
print("\nNumerical Summary")
display(df.describe())

Numerical Summary

,fiscal_year_start,ctas_urgency_score,ed_visits,median_los_minutes,median_los_hours
count,912.000000,912.000000,9.120000e+02,912.000000,912.000000
mean,2012.000000,2.500000,1.927225e+05,166.116228,2.768553
std,5.480231,0.764182,2.169945e+05,94.261307,1.570923
min,2003.000000,1.000000,4.500000e+01,10.000000,0.170000
25%,2007.000000,2.000000,1.399225e+04,84.000000,1.400000
50%,2012.000000,3.000000,1.049835e+05,144.000000,2.400000
75%,2017.000000,3.000000,3.000808e+05,235.000000,3.920000
max,2021.000000,3.000000,1.165671e+06,420.000000,7.000000

In [26]:
print("\nSex Distribution")
display(df["sex"].value_counts())

print("\nCTAS Distribution")
display(df["triage_level"].value_counts())

print("\nAge Group Distribution")
display(df["age_group"].value_counts())

print("\nPopulation Category Distribution")
display(df["population_category"].value_counts())

Sex Distribution

sex
Female    456
Male      456
Name: count, dtype: int64

CTAS Distribution

triage_level
CTAS I - Resuscitation    152
CTAS II - Emergent        152
CTAS III - Urgent         152
Less urgent               152
Non-urgent                152
Unknown                   152
Name: count, dtype: int64

Age Group Distribution

age_group
00–19    228
20–44    228
45–64    228
65+      228
Name: count, dtype: int64

Population Category Distribution

population_category
Pediatric & Youth    228
Young Adult          228
Middle Adult         228
Older Adult          228
Name: count, dtype: int64

In [27]:
print("\nFirst 20 Rows")
display(df.head(20))

print("\nLast 20 Rows")
display(df.tail(20))

print("\nRandom Sample")
display(df.sample(10, random_state=42))

First 20 Rows

,fiscal_year,fiscal_year_start,sex,triage_level,ctas_urgency_score,age_group,population_category,ed_visits,median_los_minutes,median_los_hours
0,2021-2022,2021,Female,CTAS I - Resuscitation,1,00–19,Pediatric & Youth,10332,240,4.0
1,2021-2022,2021,Female,CTAS I - Resuscitation,1,20–44,Young Adult,11051,330,5.5
2,2021-2022,2021,Female,CTAS I - Resuscitation,1,45–64,Middle Adult,11653,324,5.4
3,2021-2022,2021,Female,CTAS I - Resuscitation,1,65+,Older Adult,25787,414,6.9
4,2021-2022,2021,Male,CTAS I - Resuscitation,1,00–19,Pediatric & Youth,12409,228,3.8
5,2021-2022,2021,Male,CTAS I - Resuscitation,1,20–44,Young Adult,18848,336,5.6
6,2021-2022,2021,Male,CTAS I - Resuscitation,1,45–64,Middle Adult,20762,300,5.0
7,2021-2022,2021,Male,CTAS I - Resuscitation,1,65+,Older Adult,30338,360,6.0
8,2021-2022,2021,Female,CTAS II - Emergent,2,00–19,Pediatric & Youth,208386,228,3.8
9,2021-2022,2021,Female,CTAS II - Emergent,2,20–44,Young Adult,416879,282,4.7
10,2021-2022,2021,Female,CTAS II - Emergent,2,45–64,Middle Adult,314935,306,5.1
11,2021-2022,2021,Female,CTAS II - Emergent,2,65+,Older Adult,352317,414,6.9
12,2021-2022,2021,Male,CTAS II - Emergent,2,00–19,Pediatric & Youth,212432,210,3.5
13,2021-2022,2021,Male,CTAS II - Emergent,2,20–44,Young Adult,361926,270,4.5
14,2021-2022,2021,Male,CTAS II - Emergent,2,45–64,Middle Adult,341235,318,5.3
15,2021-2022,2021,Male,CTAS II - Emergent,2,65+,Older Adult,341652,414,6.9
16,2021-2022,2021,Female,CTAS III - Urgent,3,00–19,Pediatric & Youth,545195,180,3.0
17,2021-2022,2021,Female,Less urgent,3,00–19,Pediatric & Youth,398170,144,2.4
18,2021-2022,2021,Female,Non-urgent,3,00–19,Pediatric & Youth,121024,120,2.0
19,2021-2022,2021,Female,Unknown,3,00–19,Pediatric & Youth,10712,78,1.3

Last 20 Rows

,fiscal_year,fiscal_year_start,sex,triage_level,ctas_urgency_score,age_group,population_category,ed_visits,median_los_minutes,median_los_hours
892,2003-2004,2003,Female,CTAS III - Urgent,3,65+,Older Adult,212061,264,4.40
893,2003-2004,2003,Female,Less urgent,3,65+,Older Adult,147221,140,2.33
894,2003-2004,2003,Female,Non-urgent,3,65+,Older Adult,49746,75,1.25
895,2003-2004,2003,Female,Unknown,3,65+,Older Adult,45,36,0.60
896,2003-2004,2003,Male,CTAS III - Urgent,3,00–19,Pediatric & Youth,216494,130,2.17
897,2003-2004,2003,Male,Less urgent,3,00–19,Pediatric & Youth,350889,90,1.50
898,2003-2004,2003,Male,Non-urgent,3,00–19,Pediatric & Youth,94000,65,1.08
899,2003-2004,2003,Male,Unknown,3,00–19,Pediatric & Youth,201,35,0.58
900,2003-2004,2003,Male,CTAS III - Urgent,3,20–44,Young Adult,242597,168,2.80
901,2003-2004,2003,Male,Less urgent,3,20–44,Young Adult,388879,102,1.70
902,2003-2004,2003,Male,Non-urgent,3,20–44,Young Adult,137821,72,1.20
903,2003-2004,2003,Male,Unknown,3,20–44,Young Adult,264,31,0.52
904,2003-2004,2003,Male,CTAS III - Urgent,3,45–64,Middle Adult,171087,200,3.33
905,2003-2004,2003,Male,Less urgent,3,45–64,Middle Adult,194578,105,1.75
906,2003-2004,2003,Male,Non-urgent,3,45–64,Middle Adult,82423,67,1.12
907,2003-2004,2003,Male,Unknown,3,45–64,Middle Adult,103,44,0.73
908,2003-2004,2003,Male,CTAS III - Urgent,3,65+,Older Adult,168123,252,4.20
909,2003-2004,2003,Male,Less urgent,3,65+,Older Adult,114653,129,2.15
910,2003-2004,2003,Male,Non-urgent,3,65+,Older Adult,48303,66,1.10
911,2003-2004,2003,Male,Unknown,3,65+,Older Adult,50,27,0.45

Random Sample

,fiscal_year,fiscal_year_start,sex,triage_level,ctas_urgency_score,age_group,population_category,ed_visits,median_los_minutes,median_los_hours
649,2008-2009,2008,Female,Less urgent,3,45–64,Middle Adult,251071,117,1.95
761,2006-2007,2006,Male,Less urgent,3,45–64,Middle Adult,225991,110,1.83
545,2010-2011,2010,Female,Less urgent,3,00–19,Pediatric & Youth,427632,99,1.65
367,2014-2015,2014,Female,Unknown,3,65+,Older Adult,11908,102,1.70
361,2014-2015,2014,Female,Less urgent,3,45–64,Middle Adult,411256,114,1.90
849,2004-2005,2004,Male,Less urgent,3,00–19,Pediatric & Youth,343044,93,1.55
314,2015-2016,2015,Female,Non-urgent,3,45–64,Middle Adult,81133,84,1.40
659,2008-2009,2008,Male,Unknown,3,00–19,Pediatric & Youth,1213,39,0.65
254,2016-2017,2016,Male,CTAS II - Emergent,2,45–64,Middle Adult,273259,288,4.80
30,2021-2022,2021,Female,Non-urgent,3,65+,Older Adult,115897,126,2.10

In [28]:
print("\nSaving Dataset...")

df.to_csv(
    OUTPUT_FILE,
    index=False
)

print("Dataset Saved Successfully.")

print("\nSaved Location")
print(OUTPUT_FILE)

Saving Dataset...
Dataset Saved Successfully.

Saved Location
C:\Users\bhara\OneDrive\Desktop\DAMO-699-Capstone-Project-Unofficial-\DAMO-699-Capstone-Project-Unofficial-\data\Explorer Dataset\CTAS_Triage.csv